#!/bin/bash

export SERVERIP=`hostname -I`
#export BOARDIP=192.168.1.

# Uncomment when using a build server #
#export USE_BUILD_SERVER=build.baylibre.com
#export CROSS_COMPILE=arm-linux-gnueabihf-

export CROSS_COMPILE=arm-linux-gnueabihf-
export ARCH=arm
export PATH=/opt/toolchains/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf/bin/:$PATH

export TOPLEVEL=`pwd`

export IMAGES=$TOPLEVEL/images
export TFTP_DIR=/var/lib/tftpboot/odroid

export KERNEL_SRC=$TOPLEVEL/linux
export UBOOT_SRC=$TOPLEVEL/u-boot

export INSTALL_MOD_PATH=$TOPLEVEL/rootfs
mkdir -p $INSTALL_MOD_PATH
